//! Typed enums and structures for representing calculator error and warning messages.
//!
//! Ported from `includes.h` and `Calculator.h`.

/// The severity level of a calculator message.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(i32)]
pub enum MessageType {
    /// Information message.
    Information = 0,
    /// Warning message (default).
    Warning = 1,
    /// Fatal or non-fatal error message.
    Error = 2,
}

/// The stage of calculation or conversion during which the message was generated.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum MessageStage {
    /// Stage: unit or base conversion.
    Conversion = -4,
    /// Stage: parsing during unit/base conversion.
    ConversionParsing = -3,
    /// Stage: mathematical calculation.
    Calculation = -2,
    /// Stage: expression parsing.
    Parsing = -1,
    /// Stage: unset or default.
    Unset = 0,
}

/// The category of a message, allowing classification of errors and warnings.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum MessageCategory {
    /// No specific category.
    None = 0,
    /// Parsing category.
    Parsing = 1,
    /// Wide interval warning.
    WideInterval = 10,
    /// Implicit multiplication disambiguation.
    ImplicitMultiplication = 11,
    /// Unsupported interval calculation feature.
    NoProperIntervalSupport = 12,
    /// Reference to a deactivated global object.
    GlobalObjectDeactivated = 13,
}

/// A structured warning or error message generated by the calculator.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CalculatorMessage {
    message: String,
    message_type: MessageType,
    category: MessageCategory,
    stage: MessageStage,
}

impl CalculatorMessage {
    /// Create a new `CalculatorMessage`.
    pub fn new(
        message: String,
        message_type: MessageType,
        category: MessageCategory,
        stage: MessageStage,
    ) -> Self {
        Self {
            message,
            message_type,
            category,
            stage,
        }
    }

    /// Get the message text.
    pub fn message(&self) -> &str {
        &self.message
    }

    /// Get the message type/severity.
    pub fn message_type(&self) -> MessageType {
        self.message_type
    }

    /// Get the message category.
    pub fn category(&self) -> MessageCategory {
        self.category
    }

    /// Get the stage of calculation.
    pub fn stage(&self) -> MessageStage {
        self.stage
    }
}

/// A queue of `CalculatorMessage`s representing warnings and errors from the current session.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct MessageQueue {
    messages: Vec<CalculatorMessage>,
}

impl MessageQueue {
    /// Create a new empty message queue.
    pub fn new() -> Self {
        Self::default()
    }

    /// Push a message onto the end of the queue.
    pub fn push(&mut self, message: CalculatorMessage) {
        self.messages.push(message);
    }

    /// Check if the queue is empty.
    pub fn is_empty(&self) -> bool {
        self.messages.is_empty()
    }

    /// Get the number of messages in the queue.
    pub fn len(&self) -> usize {
        self.messages.len()
    }

    /// Get a reference to the first/oldest message in the queue if it exists.
    pub fn message(&self) -> Option<&CalculatorMessage> {
        self.messages.first()
    }

    /// Remove and return the first/oldest message in the queue.
    pub fn next_message(&mut self) -> Option<CalculatorMessage> {
        if !self.messages.is_empty() {
            Some(self.messages.remove(0))
        } else {
            None
        }
    }

    /// Clear all messages in the queue.
    pub fn clear(&mut self) {
        self.messages.clear();
    }

    /// Get a read-only slice of all messages currently in the queue.
    pub fn get_messages(&self) -> &[CalculatorMessage] {
        &self.messages
    }
}
