//! Typed enums and structures for representing calculator error and warning messages.
//!
//! Ported from `includes.h` and `Calculator.h`.

/// The severity level of a calculator message.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(i32)]
pub enum MessageType {
    /// Information message.
    Information = 0,
    /// Warning message (default).
    Warning = 1,
    /// Fatal or non-fatal error message.
    Error = 2,
}

impl MessageType {
    /// Return the qalc line prefix for this severity.
    ///
    /// Upstream prints informational messages as bare text; warnings and errors
    /// carry an explicit severity prefix.
    pub const fn qalc_prefix(self) -> Option<&'static str> {
        match self {
            Self::Information => None,
            Self::Warning => Some("warning"),
            Self::Error => Some("error"),
        }
    }
}

/// The stage of calculation or conversion during which the message was generated.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum MessageStage {
    /// Stage: unit or base conversion.
    Conversion = -4,
    /// Stage: parsing during unit/base conversion.
    ConversionParsing = -3,
    /// Stage: mathematical calculation.
    Calculation = -2,
    /// Stage: expression parsing.
    Parsing = -1,
    /// Stage: unset or default.
    Unset = 0,
}

/// The category of a message, allowing classification of errors and warnings.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum MessageCategory {
    /// No specific category.
    None = 0,
    /// Parsing category.
    Parsing = 1,
    /// Wide interval warning.
    WideInterval = 10,
    /// Implicit multiplication disambiguation.
    ImplicitMultiplication = 11,
    /// Unsupported interval calculation feature.
    NoProperIntervalSupport = 12,
    /// Reference to a deactivated global object.
    GlobalObjectDeactivated = 13,
}

/// A structured warning or error message generated by the calculator.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CalculatorMessage {
    message: String,
    message_type: MessageType,
    category: MessageCategory,
    stage: MessageStage,
}

impl CalculatorMessage {
    /// Create a new `CalculatorMessage`.
    pub fn new(
        message: String,
        message_type: MessageType,
        category: MessageCategory,
        stage: MessageStage,
    ) -> Self {
        Self {
            message,
            message_type,
            category,
            stage,
        }
    }

    /// Get the message text.
    pub fn message(&self) -> &str {
        &self.message
    }

    /// Get the message type/severity.
    pub fn message_type(&self) -> MessageType {
        self.message_type
    }

    /// Get the message category.
    pub fn category(&self) -> MessageCategory {
        self.category
    }

    /// Get the stage of calculation.
    pub fn stage(&self) -> MessageStage {
        self.stage
    }

    /// Format this message as a qalc-compatible diagnostic line.
    pub fn to_qalc_line(&self) -> String {
        match self.message_type.qalc_prefix() {
            Some(prefix) => format!("{prefix}: {}", self.message),
            None => self.message.clone(),
        }
    }
}

/// A queue of `CalculatorMessage`s representing warnings and errors from the current session.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct MessageQueue {
    messages: Vec<CalculatorMessage>,
}

impl MessageQueue {
    /// Create a new empty message queue.
    pub fn new() -> Self {
        Self::default()
    }

    /// Push a message onto the end of the queue.
    pub fn push(&mut self, message: CalculatorMessage) {
        self.messages.push(message);
    }

    /// Check if the queue is empty.
    pub fn is_empty(&self) -> bool {
        self.messages.is_empty()
    }

    /// Get the number of messages in the queue.
    pub fn len(&self) -> usize {
        self.messages.len()
    }

    /// Get a reference to the first/oldest message in the queue if it exists.
    pub fn message(&self) -> Option<&CalculatorMessage> {
        self.messages.first()
    }

    /// Remove and return the first/oldest message in the queue.
    pub fn next_message(&mut self) -> Option<CalculatorMessage> {
        if !self.messages.is_empty() {
            Some(self.messages.remove(0))
        } else {
            None
        }
    }

    /// Drain messages in FIFO order, formatting each line like qalc output.
    pub fn drain_qalc_lines(&mut self) -> Vec<String> {
        std::mem::take(&mut self.messages)
            .into_iter()
            .map(|message| message.to_qalc_line())
            .collect()
    }

    /// Clear all messages in the queue.
    pub fn clear(&mut self) {
        self.messages.clear();
    }

    /// Get a read-only slice of all messages currently in the queue.
    pub fn get_messages(&self) -> &[CalculatorMessage] {
        &self.messages
    }
}

#[cfg(test)]
mod tests {
    use super::{CalculatorMessage, MessageCategory, MessageQueue, MessageStage, MessageType};

    #[test]
    fn message_types_map_to_qalc_prefixes() {
        assert_eq!(MessageType::Information.qalc_prefix(), None);
        assert_eq!(MessageType::Warning.qalc_prefix(), Some("warning"));
        assert_eq!(MessageType::Error.qalc_prefix(), Some("error"));
    }

    #[test]
    fn messages_format_as_qalc_lines() {
        let info = CalculatorMessage::new(
            "loaded".to_string(),
            MessageType::Information,
            MessageCategory::None,
            MessageStage::Calculation,
        );
        let warning = CalculatorMessage::new(
            "ambiguous input".to_string(),
            MessageType::Warning,
            MessageCategory::ImplicitMultiplication,
            MessageStage::Parsing,
        );
        let error = CalculatorMessage::new(
            "invalid expression".to_string(),
            MessageType::Error,
            MessageCategory::Parsing,
            MessageStage::Parsing,
        );

        assert_eq!(info.to_qalc_line(), "loaded");
        assert_eq!(warning.to_qalc_line(), "warning: ambiguous input");
        assert_eq!(error.to_qalc_line(), "error: invalid expression");
    }

    #[test]
    fn draining_qalc_lines_preserves_order_and_clears_queue() {
        let mut queue = MessageQueue::new();
        queue.push(CalculatorMessage::new(
            "first".to_string(),
            MessageType::Information,
            MessageCategory::None,
            MessageStage::Calculation,
        ));
        queue.push(CalculatorMessage::new(
            "second".to_string(),
            MessageType::Warning,
            MessageCategory::None,
            MessageStage::Calculation,
        ));
        queue.push(CalculatorMessage::new(
            "third".to_string(),
            MessageType::Error,
            MessageCategory::None,
            MessageStage::Calculation,
        ));

        assert_eq!(
            queue.drain_qalc_lines(),
            ["first", "warning: second", "error: third"]
        );
        assert!(queue.is_empty());
        assert!(queue.drain_qalc_lines().is_empty());
    }
}
